// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QlySach.Models;

namespace QlySach.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201113022525_seeder_table_Book")]
    partial class seeder_table_Book
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QlySach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicYear")
                        .HasColumnType("int");

                    b.Property<string>("ShortContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20,
                            Author = "Nguyễn Du",
                            CategoryId = 2,
                            Name = "Truyện Kiều",
                            PublicYear = 1696,
                            ShortContent = "Longtime no see"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30,
                            Author = "Thomas Friedman",
                            CategoryId = 1,
                            Name = "Thế Giới Phẳng",
                            PublicYear = 2006,
                            ShortContent = "Longtime no see"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 10,
                            Author = "Aristotle",
                            CategoryId = 3,
                            Name = "Chính trị Luận",
                            PublicYear = 1995,
                            ShortContent = "Longtime no see"
                        });
                });

            modelBuilder.Entity("QlySach.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Kinh tế"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Văn Học"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Chính trị"
                        });
                });

            modelBuilder.Entity("QlySach.Models.Book", b =>
                {
                    b.HasOne("QlySach.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QlySach.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
